#include "order_book.h"
#include <iostream>
#include <vector>
#include <random>
#include <chrono>
#include <algorithm>
#include <tuple>

int main() {

    std::ios::sync_with_stdio(false);
    std::cin.tie(nullptr);

    OrderBook ob(0.0, 1000.0, 100.0);

    const int NUM_ORDERS = 200000;
    std::vector<Order> orders;
    orders.reserve(NUM_ORDERS);

    // ---------------- RANDOM ORDER GENERATION ----------------
    std::mt19937 rng(42);
    std::uniform_real_distribution<> priceDist(90, 110);
    std::uniform_int_distribution<> qtyDist(1, 100);
    std::uniform_int_distribution<> sideDist(0, 99);

    for(int i = 1; i <= NUM_ORDERS; i++) {
        Order o;
        o.id = i;

        if(sideDist(rng) < 70)
            o.side = Side::BUY;
        else
            o.side = Side::SELL;

        o.price = priceDist(rng);
        o.quantity = qtyDist(rng);
        o.type = OrderType::LIMIT;

        orders.push_back(o);
    }

    // ---------------- BENCHMARK START ----------------
    long long totalOrders = 0;   //  NEW

    auto start = std::chrono::high_resolution_clock::now();

    for(int i = 0; i < NUM_ORDERS; i++) {

        ob.addLimitOrder(orders[i]);
        totalOrders++;   //  COUNT NORMAL ORDER

        // BURST every 1000 orders
        if(i > 0 && i % 1000 == 0) {

            for(int j = 0; j < 100 && i + j < NUM_ORDERS; j++) {
                ob.addLimitOrder(orders[i + j]);
                totalOrders++;   //  COUNT BURST ORDERS
            }
        }
    }

    auto end = std::chrono::high_resolution_clock::now();

    // ---------------- BENCHMARK RESULTS ----------------
    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();

    std::cout << "\n===== HFT BENCHMARK =====\n";
    std::cout << "Orders Processed: " << totalOrders << "\n";   //  FIXED
    std::cout << "Time Taken: " << duration << " ms\n";
    std::cout << "Throughput: "
              << (totalOrders * 1000LL / std::max(1LL, duration))
              << " orders/sec\n";   //  FIXED

    ob.printThroughput();

    return 0;
}
































// below is nput output generated by user above is in bulk auto generated
// #include "order_book.h"
// #include <iostream>
// #include <string>

// int main() {

//     std::ios::sync_with_stdio(false);
//     std::cin.tie(nullptr);

//     OrderBook ob(0.0, 1000.0, 100.0);

//     std::string command;

//     while (true) {

//         std::cin >> command;

//         if(command == "ADD") {

//             int id;
//             std::string sideStr, type;

//             std::cin >> id >> sideStr >> type;

//             Side side = (sideStr == "BUY") ? Side::BUY : Side::SELL;

//             if(type == "LIMIT") {

//                 double price;
//                 int quantity;
//                 std::cin >> price >> quantity;

//                 Order order{id, side, price, quantity, OrderType::LIMIT};
//                 ob.addLimitOrder(order);

//             } else if(type == "MARKET") {

//                 int quantity;
//                 std::cin >> quantity;
//                 ob.executeMarketOrder(side, quantity);
//             }
//         }

//         else if (command == "CANCEL") {

//             int id;
//             std::cin >> id;
//             ob.cancelOrder(id);

//         }

//         else if (command == "PRINT") {
//             ob.printBook();
//         }

//         else if (command == "TRADES") {
//             ob.printTrades();
//         }

//         else if (command == "SIM") {

//             for(int i = 1; i <= 100000; i++) {
//                 Order order{
//                     i,
//                     (i % 2 == 0) ? Side::BUY : Side::SELL,
//                     100 + (i % 50),
//                     10,
//                     OrderType::LIMIT
//                 };

//                 ob.addLimitOrder(order);
//             }
// // 
//             std::cout << "Simulation completed\n";
//         }

//         else if (command == "STATS") {
//             ob.printThroughput();
//         }

//         else if (command == "EXIT") {
//             ob.printThroughput();
//             break;
//         }

//         else {
//             std::cout << "Invalid command\n";
//         }
//     }

//     return 0;
// }